# https://starship.rs/config

format = """
$hostname\
($shell)\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

right_format = """$time"""

[hostname]
ssh_only = false
style = 'dimmed italic purple'
format = '[$hostname]($style) '

[shell]
format = '[\($indicator\)]($style) '
style = 'dimmed purple'
disabled = false

[fill]
symbol = ' '

[directory]
style = "purple"
truncate_to_repo = false
truncation_length = 5

[directory.substitutions]
'/_/' = ''

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
format = "$symbol[$branch]($style)"
style = 'dimmed cyan'

[git_status]
format = "[ $all_status $ahead_behind$ahead_count$behind_count]($style)"
style = "cyan"
deleted = ''
stashed = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
show_milliseconds = true

[time]
format = '[$time]($style)'
disabled = false
style = 'dimmed white'
